//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Request_Details = new HashSet<Request_Details>();
        }
    
        public int request_id { get; set; }
        public string username { get; set; }
        public string dept_code { get; set; }
        public string reason { get; set; }
        public string current_status { get; set; }
        public string rejected { get; set; }
        public string rejected_reason { get; set; }
        public string deleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Dept_Registry Dept_Registry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Details> Request_Details { get; set; }
    }
}
