//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Inventory()
        {
            this.Adjustment_Details = new HashSet<Adjustment_Details>();
            this.Alerts = new HashSet<Alert>();
            this.Favourites = new HashSet<Favourite>();
            this.Request_Details = new HashSet<Request_Details>();
            this.Tender_List_Details = new HashSet<Tender_List_Details>();
        }
    
        public string item_code { get; set; }
        public int current_qty { get; set; }
        public int reorder_qty { get; set; }
        public int reorder_level { get; set; }
        public string supplier_id { get; set; }
        public string unit_of_measure { get; set; }
        public string item_description { get; set; }
        public string image_path { get; set; }
        public string deleted { get; set; }
        public int cat_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment_Details> Adjustment_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite> Favourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Details> Request_Details { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tender_List_Details> Tender_List_Details { get; set; }
    }
}
