//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval_Duties
    {
        public string username { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string dept_code { get; set; }
        public int duty_id { get; set; }
        public System.DateTime created_date { get; set; }
        public string deleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Dept_Registry Dept_Registry { get; set; }
    }
}
