//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery_Orders()
        {
            this.Delivery_Details = new HashSet<Delivery_Details>();
        }
    
        public int delivery_id { get; set; }
        public string clerk_user { get; set; }
        public System.DateTime receive_date { get; set; }
        public int order_id { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Details> Delivery_Details { get; set; }
        public virtual Dept_Registry Dept_Registry { get; set; }
        public virtual Purchase_Order Purchase_Order { get; set; }
    }
}
