//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Requests = new HashSet<Request>();
            this.Approval_Duties = new HashSet<Approval_Duties>();
        }
    
        public string dept_code { get; set; }
        public string name { get; set; }
        public string rep_user { get; set; }
        public string contact_user { get; set; }
        public string contact_num { get; set; }
        public string fax_num { get; set; }
        public string head_user { get; set; }
        public int collection_point { get; set; }
        public string logo_path { get; set; }
        public string deleted { get; set; }
    
        public virtual Collection_Point Collection_Point1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approval_Duties> Approval_Duties { get; set; }
    }
}
