//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int favourite_id { get; set; }
        public string username { get; set; }
        public string item_code { get; set; }
    
        public virtual Dept_Registry Dept_Registry { get; set; }
        public virtual Stock_Inventory Stock_Inventory { get; set; }
    }
}
