//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Adjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Adjustment()
        {
            this.Adjustment_Details = new HashSet<Adjustment_Details>();
        }
    
        public int voucher_id { get; set; }
        public string clerk_user { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public System.DateTime status_date { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment_Details> Adjustment_Details { get; set; }
    }
}
