//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Check_Records
    {
        public int check_id { get; set; }
        public System.DateTime date_checked { get; set; }
        public string clerk_user { get; set; }
        public string discrepancy { get; set; }
        public string deleted { get; set; }
    
        public virtual Dept_Registry Dept_Registry { get; set; }
    }
}
