//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order_Details
    {
        public int order_details_id { get; set; }
        public int tender_id { get; set; }
        public int quantity { get; set; }
        public int order_id { get; set; }
        public string status { get; set; }
        public string cancelled { get; set; }
        public string deleted { get; set; }
    
        public virtual Purchase_Order Purchase_Order { get; set; }
        public virtual Tender_List_Details Tender_List_Details { get; set; }
    }
}
