//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender_List_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tender_List_Details()
        {
            this.Delivery_Details = new HashSet<Delivery_Details>();
            this.Purchase_Order_Details = new HashSet<Purchase_Order_Details>();
        }
    
        public int tender_id { get; set; }
        public decimal price { get; set; }
        public int rank { get; set; }
        public int tender_year_id { get; set; }
        public string item_code { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Details> Delivery_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order_Details> Purchase_Order_Details { get; set; }
        public virtual Stock_Inventory Stock_Inventory { get; set; }
        public virtual Tender_List Tender_List { get; set; }
        public virtual Tender_List Tender_List1 { get; set; }
    }
}
