//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tender_List()
        {
            this.Tender_List_Details = new HashSet<Tender_List_Details>();
        }
    
        public int tender_year_id { get; set; }
        public string supplier_id { get; set; }
        public System.DateTime tender_date { get; set; }
        public int tender_id { get; set; }
        public string deleted { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tender_List_Details> Tender_List_Details { get; set; }
        public virtual Tender_List_Details Tender_List_Details1 { get; set; }
    }
}
