//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSISTeam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume_Request
    {
        public string cat_name { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public System.DateTime date_time { get; set; }
        public string item_description { get; set; }
        public string username { get; set; }
        public string dept_code { get; set; }
        public string status { get; set; }
        public string current_status { get; set; }
        public string item_code { get; set; }
    }
}
